title: Bistro
modelClass: Stagesolutions\Bargeld\Models\Bistro
list: $/stagesolutions/bargeld/models/bistro/columns.yaml
recordUrl: 'stagesolutions/bargeld/bistro/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
