list: $/stagesolutions/bargeld/models/receipts/columns.yaml
modelClass: Stagesolutions\Bargeld\Models\Receipts
title: Receipts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'stagesolutions/bargeld/receipts/update/:id'
