list: $/stagesolutions/bargeld/models/other/columns.yaml
modelClass: Stagesolutions\Bargeld\Models\Other
title: Other
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'stagesolutions/bargeld/other/update/:id'
